version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:lastest

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm i
      - run: npm build
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
        root: ~/repo
        paths: .

  release:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm build
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          requires:
            - test
